export type HelpArticle = { id: string; title: string; body: string; terms: string[] };
export const articles: HelpArticle[] = [
 {id:'review',title:'Como funciona a revisão dos resultados?',body:'Cada grupo reúne o valor encontrado; marque apenas as ocorrências que deseja editar. Revisados inclui marcações manuais e aplicações verificadas, que são registros distintos. Variáveis criadas mostra apenas as originadas naquele scan. Os resultados salvos não são uma consulta ao CMS atual. Para buscar mudanças externas, inicie outro scan; para reverter uma alteração, confira e confirme o conteúdo pelo fluxo de reversão.',terms:['revisao','review','revisados','resultados','results']},
 {id:'static',title:'Como buscar texto em páginas estáticas?',body:'Abra a extensão ReplaceAll dentro do Webflow Designer, na página desejada. Escolha Texto, informe o termo e busque. Selecione as ocorrências e edite vendo o resultado no contexto. Confirme para aplicar. A busca cobre o conteúdo suportado da página aberta, não todo o site publicado.',terms:['estatico','estatica','estaticos','estaticas','estaticamente','static','designer','pagina','page','extension','extensao']},
 {id:'cms',title:'Como buscar texto no CMS?',body:'No dashboard, abra seu site → Scans → Novo scan. Escolha as coleções e o modo Texto, digite o termo e inicie a busca. Revise as ocorrências encontradas. O dashboard precisa permanecer visível e online para executar os lotes do scan.',terms:['cms','colecao','collection','scan','buscar','pesquisar','search','find']},
 {id:'replace',title:'Como substituir apenas as ocorrências escolhidas?',body:'Marque as ocorrências na lista à esquerda. Preencha Substituir por e veja Antes e Novo valor. Use Editar individualmente para valores diferentes. Confira os campos afetados e clique em Aplicar alterações. A edição local não altera o Webflow até a confirmação.',terms:['substituir','replace','editar','edit','individualmente','selecionar','selection','preview','previa']},
 {id:'variable',title:'Como criar uma Variável?',body:'Selecione ao menos duas ocorrências elegíveis no scan. No fluxo de confirmação, escolha criar uma Variável e informe um nome. Confira o valor e as fontes antes de confirmar. Variáveis criadas mostra apenas as originadas naquele scan; o catálogo completo fica em Variáveis.',terms:['variavel','variaveis','variable','variables','centralizar','vinculo','binding']},
 {id:'connect',title:'Como conectar meu site Webflow?',body:'Escolha um workspace e abra a conexão Webflow. Autorize os sites desejados; os permitidos serão vinculados automaticamente ao retornar. Entrar com Webflow autentica sua conta, mas a conexão CMS é separada. Um site já vinculado a outro workspace deve ser transferido.',terms:['conectar','connect','webflow','oauth','autorizar','workspace','transferir']},
 {id:'limit',title:'Por que não consigo conectar outro site?',body:'O plano gratuito permite um site Webflow por conta, somando todos os workspaces. Criar outro workspace não amplia a cota. Ao atingir o limite, você ainda pode reconectar seu site existente. Consulte Plano e consumo no dashboard.',terms:['limite','limit','quota','cota','plano','plan','outro','another']},
 {id:'password',title:'Como recuperar minha senha?',body:'Na tela de login, use Esqueceu sua senha e informe seu e-mail. Aguarde a mensagem e confira o spam. Use o link mais recente para definir a nova senha. Nunca envie sua senha, token ou link de recuperação ao suporte.',terms:['senha','password','reset','recuperar','login','email','entrar']},
 {id:'progress',title:'Posso fechar o navegador durante uma operação?',body:'Alterações CMS já confirmadas continuam no worker em segundo plano. Scans dependem do dashboard visível e online. A extensão precisa do contexto do Designer para editar a página. Consulte o Histórico e atualize a página para verificar resultados; um conflito ou resultado incerto não significa sucesso.',terms:['progresso','progress','worker','fila','queue','demora','travado','background','fechar']},
 {id:'conflict',title:'O que fazer quando aparece um conflito?',body:'Um conflito indica que a evidência ou o conteúdo mudou. Revise a fonte atual e prepare novamente a alteração pelo fluxo indicado. Para fontes de Variáveis, use a área de Variáveis. Não repita uma escrita com resultado incerto: ela precisa ser reconciliada. Se o problema persistir, abra um chamado.',terms:['conflito','conflict','erro','error','incerto','uncertain','falha','failed']},
 {id:'images',title:'Como trocar uma imagem ou um link?',body:'Busque no modo Imagens ou Links e selecione as ocorrências elegíveis. Informe a nova URL, confira o resultado e confirme. Imagens são comparadas por URL, não por semelhança visual. A alteração não publica o site automaticamente.',terms:['imagem','imagens','image','images','gallery','galeria','link','url','foto']},
 {id:'saved',title:'A busca rápida consulta o site ao vivo?',body:'Não. A busca rápida consulta registros de scans salvos e informa sua cobertura. Para obter conteúdo atual do CMS, inicie um novo scan no escopo desejado. Não encontrar um resultado salvo não comprova que ele não existe no site.',terms:['rapida','quick','salvo','saved','atual','live','historico','history']},
];
