import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { beforeAll,afterAll,it,expect } from 'vitest';
let db:PGlite;
const owner=randomUUID(),other=randomUUID(),admin=randomUUID(),request=randomUUID();let ticket:number;
async function actor(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;create schema app_private;grant usage on schema app_private to authenticated;create function app_private.is_admin(actor uuid) returns boolean language sql stable as $$select actor='${admin}'::uuid$$;insert into auth.users values('${owner}'),('${other}'),('${admin}');`);await db.exec('revoke all on all functions in schema app_private from public,anon,authenticated');await db.exec(readFileSync('supabase/migrations/20260930000100_support_tickets.sql','utf8'));},20000);
afterAll(async()=>{await db.close();});
it('creates one ticket/message for repeated submission and rejects changed payload',async()=>{await actor(owner);const create=()=>db.query<{id:number}>("select public.create_support_ticket($1,'question','Question','Body') id",[request]);ticket=(await create()).rows[0]!.id;expect((await create()).rows[0]!.id).toBe(ticket);expect((await db.query('select * from support_messages')).rows).toHaveLength(1);await expect(db.query("select public.create_support_ticket($1,'problem','Changed','Body')",[request])).rejects.toThrow('SUPPORT_CONFLICT');});
it('isolates customers, rejects guessed ticket writes and staff status escalation',async()=>{await actor(other);expect((await db.query('select * from support_tickets')).rows).toHaveLength(0);expect((await db.query('select * from support_messages')).rows).toHaveLength(0);await expect(db.query("select reply_support_ticket($1,$2,'hello','open')",[randomUUID(),ticket])).rejects.toThrow('SUPPORT_DENIED');await actor(owner);await expect(db.query("select reply_support_ticket($1,$2,'hello','resolved')",[randomUUID(),ticket])).rejects.toThrow('SUPPORT_DENIED');await expect(db.query("update support_tickets set status='resolved'")).rejects.toThrow();});
it('allows admin reply, records status evidence and preserves idempotency',async()=>{await actor(admin);expect((await db.query('select * from support_tickets')).rows).toHaveLength(1);const key=randomUUID();for(let i=0;i<2;i++)await db.query("select reply_support_ticket($1,$2,'Resolved explanation','resolved')",[key,ticket]);expect((await db.query<{status:string}>('select status from support_tickets')).rows[0]!.status).toBe('resolved');expect((await db.query('select * from support_messages')).rows).toHaveLength(2);await actor(owner);await db.query("select reply_support_ticket($1,$2,'Still need help','open')",[randomUUID(),ticket]);expect((await db.query<{status:string}>('select status from support_tickets')).rows[0]!.status).toBe('open');});
it('denies anonymous access and invalid payloads, bounds daily admission',async()=>{await db.exec('reset role;set role anon');await expect(db.query('select * from support_tickets')).rejects.toThrow();await expect(db.query("select create_support_ticket($1,'question','Question','Body')",[randomUUID()])).rejects.toThrow();await actor(owner);await expect(db.query("select create_support_ticket($1,'question','x','Body')",[randomUUID()])).rejects.toThrow('SUPPORT_INVALID');for(let i=0;i<4;i++)await db.query("select create_support_ticket($1,'question','Question','Body')",[randomUUID()]);await expect(db.query("select create_support_ticket($1,'question','Question','Body')",[randomUUID()])).rejects.toThrow('SUPPORT_RATE');});
